apiVersion: v1
kind: ServiceAccount
metadata:
  name: spotinst-kubernetes-cluster-autoscaler-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spotinst-kubernetes-cluster-autoscaler-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spotinst-kubernetes-cluster-autoscaler-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spotinst-kubernetes-cluster-autoscaler-cluster-role
subjects:
- kind: ServiceAccount
  name: spotinst-kubernetes-cluster-autoscaler-service-account
  namespace: default

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: spotinst-kubernetes-cluster-autoscaler
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: spotinst-kubernetes-cluster-autoscaler
            image: naorlivne/spotinst_kubernetes_cluster_autoscaler
            env:
            - name: SPOTINST_TOKEN
              value: "my_super_secret_spotinst_token"
            - name: ELASTIGROUP_ID
              value: "sig-123XXXXXXXX"
            resources:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
          restartPolicy: OnFailure
          serviceAccountName: spotinst-kubernetes-cluster-autoscaler-service-account