apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: spotinst-kubernetes-cluster-autoscaler
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: spotinst-kubernetes-cluster-autoscaler
            image: naorlivne/spotinst_kubernetes_cluster_autoscaler
            env:
            - name: SPOTINST_TOKEN
              value: "my_super_secret_spotinst_token"
            - name: ELASTIGROUP_ID
              value: "sig-123XXXXXXXX"
            - name: SPOTINST_ACCOUNT
              value: "acc-123XXXXXXXX"
            resources:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
          restartPolicy: OnFailure
